#!/bin/bash

# Specify the commit message as a command-line argument
message="$1"

# Run git add .
git add .

# Run git commit -m with the specified message
git commit -m "$message"

# Run git push
git push
